services:
  nextapp:
    container_name: nextapp
    image: francescoxx/nextapp:latest
    build:
      context: ./frontend
      # dockerfile: next.dockerfile
      dockerfile: next.dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - node-modules:/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      # - NODE_ENV=production
      - NODE_ENV=development
    depends_on:
      - rustapp
  rustapp:
    container_name: rustapp
    image: francescoxx/rustapp:latest
    build:
      context: ./backend
      # dockerfile: rust.dockerfile
      dockerfile: rust.dockerfile.dev
      args:
         - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./backend:/app
      - cargo_registry:/usr/local/cargo/registry
      - cargo_git:/usr/local/cargo/git
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  cargo_registry:
  cargo_git:
  node-modules: